### ISSUE TITLE
s/origin-ci-tool/genesis

### ISSUE THREAD

**Issue by derekwaynecarr** [openshift/origin-ci-tool#1]
it brings origin into being ;-)

**Comment by enj** [comment]
﻿⁠⁠⁠⁠`om`﻿⁠⁠⁠⁠ may also work: https://en.wikipedia.org/wiki/Om:

> ﻿⁠⁠⁠⁠the primordial sound associated with the creation of universe from nothing﻿⁠⁠⁠⁠
