### ISSUE TITLE
Docker command fails

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin-ci-tool#108]
When running `docker` command in our AMI, I see following error:

```
[ec2-user@ip-172-18-4-73 root]$ docker
chroot: cannot change root directory to /rootfs: No such file or directory
```

Not really sure whats causing the issue, but I see it in more of our jenkins jobs

**Comment by stevekuznetsov** [comment]
This is https://bugzilla.redhat.com/show_bug.cgi?id=1455472, see also https://github.com/openshift/origin/pull/14350 where more discussion is happening.
