### ISSUE TITLE
how do i add a non-openshift repository?

### ISSUE THREAD

**Issue by bparees** [openshift/origin-ci-tool#118]
I need to support syncing/building this repo https://github.com/openshift-s2i/s2i-wildfly which isn't in the openshift org.  How do i add it as a supported repo to this tool?

@stevekuznetsov

**Comment by stevekuznetsov** [comment]
Smells like a refactor to me. Lots of logic expects repos to be under `openshift/` org.

**Comment by bparees** [comment]
fun.
