### ISSUE TITLE
Publish openshift AMI's also in other AWS regions than us-east-1

### ISSUE THREAD

**Issue by josefkarasek** [openshift/origin-ci-tool#122]
When deploying openshift on aws, the prebuilt AMI's are only available in us-east-1 region. The user experience would be much better, if it were possible to deploy the ami's also in a European aws data centre.

**Comment by stevekuznetsov** [comment]
@smarterclayton @dobbymoodge we need to determine if we still have those region limits set to 0 everywhere but `us-east-1` and also if we can get a quick job set up to mirror AMIs across regions daily or something so the devs in Europe aren't stuck. Alternatively @kargakis @mfojtik do you guys have any workarounds? Or do you just deal with the latency to `us-east-1`?

**Comment by kargakis** [comment]
Yeah, that was the main reason I could not make `oct provision` work initially, when I started playing around with it. Eventually, I realized that we publish AMIs only in `us-east-1` so I just switched my config to use that region. I don't care about the latency but then again I can't know how faster spinning up one of our AMIs in Europe is :)

**Comment by josefkarasek** [comment]
The issue is latency. I don't think that VM's spin up faster in Frankfurt ;)

**Comment by dobbymoodge** [comment]
Well, VMs nearer the equator would technically have a higher angular
velocity...

On Jul 4, 2017 9:19 AM, "Josef Karasek" <notifications@github.com> wrote:

The issue is latency. I don't think that VM's spin up faster in Frankfurt ;)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin-ci-tool/issues/122#issuecomment-312800259>,
or mute the thread

**Comment by dobbymoodge** [comment]
Is this a blocker today or an inconvenience?

**Comment by josefkarasek** [comment]
Inconvenience.

`us-east-1` works from europe, it's just far.

**Comment by stevekuznetsov** [comment]
@dobbymoodge if there is no strong reason (like, IIRC we turned our quota for EC2 to 0 in a lot of regions) I can just mirror over the AMIs between regions. I'm not sure where we stand on this though, esp. for sustainability. The latency can be an annoyance if doing UI-heavy work.

**Comment by josefkarasek** [comment]
`oc get pod` takes around 5 seconds to return
