### ISSUE TITLE
Origin --stage=install instance unusable

### ISSUE THREAD

**Issue by soltysh** [openshift/origin-ci-tool#149]
I've setup my instance with:
```
oct provision remote all-in-one --os rhel --stage install --provider aws --name mydev
```
After logging into it I could not connect to openshift. I've started digging and here are the problems:

1. etcd configured with different IP
2. missing etcd directories (`/tmp/etcd`)
3. master configured with different IP
4. node configured with different IP
5. certs generated for different IP

I was able to address 1-4, but I failed with 5th. It would be nice to have a script that addresses all that before actually starting the cluster.

**Comment by stevekuznetsov** [comment]
Yeah, sorry -- this is known. There isn't really a good way to get that stage to work and we should honestly remove it. There's no way to get certs generated for the right IP before we stop the instance and create the AMI  since we have no idea what the IP will be when it's restarted later/

**Comment by soltysh** [comment]
How about a script that will clean this and restart all the bits afterwards?

**Comment by stevekuznetsov** [comment]
One could be cobbled together from the install job, sure. Not something we should check into `oct` though, given how frequently it changes.
