### ISSUE TITLE
FYI: --process-dependency-links is deprecated

### ISSUE THREAD

**Issue by ashcrow** [openshift/origin-ci-tool#173]
## Description
Install instructions note to run:

```
    $ pip install git+https://github.com/openshift/origin-ci-tool.git --process-dependency-links
```
However, `pip` warns:

```
DEPRECATION: Dependency Links processing has been deprecated and will be removed in a future release.
```

## Versions
- `pip`: 10.0.1
- `python`: 2.7.15
- python2-virtualenv:  16.0.0-1

**Comment by stevekuznetsov** [comment]
Yeah in some documentation around this warning, it was mentioned that the feature would not be removed. It's just noise right now for installations.
