### ISSUE TITLE
Move more repo-specific configuration into repos

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin-ci-tool#29]
We should support some sort of `.oct-config` file where the following is listed:
 - which `make` targets are a `build`
 - which `make` targets are an `install`
 - which `make` targets are a `test`
 - which directories should be downloaded in the artifact download step

Maybe other stuff

**Comment by stevekuznetsov** [comment]
A command prefix for wrapping the `make` targets -- this will mean we cannot use the `make` module but that is a minor inconvenience. We should just allow for a wrapper per repo, for example `sudo` or `env` etc.

**Comment by rhcarvalho** [comment]
@stevekuznetsov could you please clarify the previous comment? What command prefix, what make module?

**Comment by stevekuznetsov** [comment]
@rhcarvalho yeah, so in Origin the `openshift/origin-release` container is now used to run most things as the container keeps the right set of dependencies in check. This means the host does not need the right version of Go, etc. So in Origin we could write that if you wanted to run `make test` we would really run `hack/env make test` as it would just run your stuff in this container instead of directly on the host.

Clayton suggested that this should just be a generic concept -- a repo may need everything to run as `sudo` (as a bad example) or with `env` (a more reasonable one). A simple example with `env` would look like this:

User enters:
```
$ oct make origin test
```

This will try to run `make test` in the Origin repository root on the remote host. The Origin `.oct-config.yml` defines a wrapper as:
```yml
---
- environment:
  env JUNIT_REPORT=true
```

This means that what actually gets run on the host is:
```
openshift/origin$ env JUNIT_REPORT=true make test
```

The more I think about it the less `make` seems natural as the interface ... but I still like the fact that it forces user interaction into single-line commands and makes the actual test steps available to developers, if instead of `oct make` we had `oct run` I can see
```
$ oct run "#!/bin/bash
some
really
complex
script
to
make
tests
happen
"
```

Being written somewhere and that isn't the best.
