### ISSUE TITLE
Issue running vibe.d web framework catridge 

### ISSUE THREAD

**Issue by aberba** [openshift/origin-ci-tool#58]
Running [this catridge](https://github.com/codeneomatrix/D-cartridge) using cli fails due to the inability to install dependencies for the [dub](code.dlang.org) package manager. ATM, there is not easy way to fix it.

**Comment by stevekuznetsov** [comment]
Is this a bug with running a cartridge on OpenShift v2? This doesn't look like the right place the file the bug -- you should post it on [BugZilla](https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Origin) and make sure to specify the version of OpenShift you are using.

**Comment by aberba** [comment]
Gush!! Bugzilla :(
