### ISSUE TITLE
Consider using git remote get-url

### ISSUE THREAD

**Issue by php-coder** [openshift/origin-ci-tool#80]
I suggest to replace command [`/usr/bin/git remote show {{ origin_ci_sync_remote }} | grep "Fetch URL" | cut -c 14- `](https://github.com/openshift/origin-ci-tool/blob/eaab752f3884c92aec726f30011469df77c09d76/oct/ansible/oct/roles/remote-sync/tasks/main.yml#L29-L30) by a more clean analogue: `/usr/bin/git remote get-url {{ origin_ci_sync_remote }}`

**Comment by stevekuznetsov** [comment]
That is much cleaner -- do you want to make a PR? Or I can take it.

**Comment by php-coder** [comment]
It's so trivial that it will be easier if you fix it.

**Comment by stevekuznetsov** [comment]
Will do. Thanks for the suggestion.
