### ISSUE TITLE
`oct build` should ensure the remote git directory is clean so tito doesn't fail

### ISSUE THREAD

**Issue by ncdc** [openshift/origin-ci-tool#89]
If the remote git directory is not clean, tito will fail. It would be nice to know about this up front, instead of having to wait over 10 minutes just to see that error 😄.

**Comment by stevekuznetsov** [comment]
Not entirely sure what the future is for commands like `oct make`, `oct build`, and `oct download` -- the higher-level discussion happened earlier and it seemed like it did not make sense to support these, instead letting users use `ssh` and `scp` as necessary to interact with the remote hosts. There may be some use for `oct` when actions need to target specific parts of a multi-node deployment, but we don't support that yet so it's not been hashed out.

**Comment by ncdc** [comment]
Ok this isn't super important if the suggestion is just to ssh in

**Comment by stevekuznetsov** [comment]
Yeah, still a TODO for me to update the docs and remove those commands.
