### ISSUE TITLE
oct make origin test-extended fails because it can't find iptables

### ISSUE THREAD

**Issue by ncdc** [openshift/origin-ci-tool#90]
It runs via `sh -c 'make test-extended'`, so I'm guessing the PATH isn't set up correctly.

**Comment by stevekuznetsov** [comment]
This was an issue with not using a login shell to run the script and the script expecting to see `/usr/sbin` in the `$PATH`. Has been fixed, but to be clear this tool just sets up an `.ssh_config`, it doesn't mediate any connections in that part.

**Comment by ncdc** [comment]
Please reopen. I hit this on master using oct by hand.

**Comment by stevekuznetsov** [comment]
Oh, sorry, you said with `oct make`.
