### ISSUE TITLE
Provide a way to reset/nuke everything

### ISSUE THREAD

**Issue by kargakis** [openshift/origin-ci-tool#93]
Give me an option to reset my config back to a default config. Also, another option is to nuke everything that is related to `oct`. These options make it easier to debug failures related to the tool and shows confidence on the tool per se.

**Comment by stevekuznetsov** [comment]
Reset config: #54 
Nuke everything: `rm -rf ~/.config/origin-ci-tool`

**Comment by kargakis** [comment]
Closing in favor of #54
